(define (problem strips-gripper-sample-2balls)
   (:domain gripper-strips)
   (:objects rooma roomb ball2 ball1 left right rob)
   (:init (robot rob)
          (room rooma)
          (room roomb)
          (ball ball2)
          (ball ball1)
          (at-robby rob rooma)
          (free left)
          (free right)
          (at ball2 rooma)
          (at ball1 rooma)
          (gripper left rob)
          (gripper right rob))
   (:goal (and
               (at ball2 roomb)
               (at ball1 roomb))))