
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem taxi-fs-3x3)
    (:domain taxi-fs)

    (:objects
        c_0_0 c_0_1 c_1_0 c_1_1 - cell
    )

    (:init
        (= (loct ) c_1_0)
        (= (locp ) c_0_0)
        (adjacent c_1_1 c_0_1)
        (adjacent c_1_1 c_1_0)
        (adjacent c_0_0 c_0_1)
        (adjacent c_0_1 c_0_0)
        (adjacent c_1_0 c_0_0)
        (adjacent c_0_0 c_1_0)
        (adjacent c_1_0 c_1_1)
        (adjacent c_0_1 c_1_1)
    )

    (:goal
        (= (locp ) c_0_1)
    )

    
    
    
)

