
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem taxi-fs-3x3)
    (:domain taxi-fs)

    (:objects
        c_0_0 c_0_1 c_0_2 c_1_0 c_1_1 c_1_2 c_2_0 c_2_1 c_2_2 - cell
        f0 f1 f10 f2 f3 f4 f5 f6 f7 f8 f9 - fuel_level
    )

    (:init
        (= (loct ) c_0_1)
        ;; (= (locp ) c_1_1)
        (= (loc_fuel ) c_1_0)
        (= (current_fuel ) f2)
        (= (min_fuel_level ) f0)
        (= (max_fuel_level ) f10)


        (adjacent c_1_2 c_1_1)
        (adjacent c_1_1 c_0_1)
        (adjacent c_1_1 c_1_0)
        (adjacent c_2_2 c_2_1)
        (adjacent c_0_0 c_0_1)
        (adjacent c_0_1 c_0_0)
        (adjacent c_0_2 c_1_2)
        (adjacent c_1_2 c_0_2)
        (adjacent c_1_0 c_0_0)
        (adjacent c_0_0 c_1_0)
        (adjacent c_2_1 c_2_2)
        (adjacent c_1_1 c_2_1)
        (adjacent c_2_0 c_1_0)
        (adjacent c_1_1 c_1_2)
        (adjacent c_1_0 c_1_1)
        (adjacent c_0_2 c_0_1)
        (adjacent c_0_1 c_0_2)
        (adjacent c_1_0 c_2_0)
        (adjacent c_0_1 c_1_1)
        (adjacent c_2_2 c_1_2)
        (adjacent c_2_0 c_2_1)
        (adjacent c_2_1 c_1_1)
        (adjacent c_2_1 c_2_0)
        (adjacent c_1_2 c_2_2)

        (succ f4 f5)
        (succ f5 f6)
        (succ f2 f3)
        (succ f0 f1)
        (succ f9 f10)
        (succ f3 f4)
        (succ f1 f2)
        (succ f8 f9)
        (succ f7 f8)
        (succ f6 f7)
    )

    (:goal
        (and (= (loct ) c_1_1))
    )

)

