(define (problem fr-4)
 (:domain first-response)
 (:objects  l1 l2 l3 l4 l5 l6  - location
	    f1 - fire_unit
	    z1 z2 z3 - victim
	    m1 m2 m3 m4 - medical_unit
)
 (:init 
	;;strategic locations
     (hospital l6)
     (hospital l1)
     (hospital l3)
     (hospital l6)
     (water-at l5)
     (water-at l2)
     (water-at l4)
	;;disaster info
     (fire l1)
     (victim-at z1 l3)
     (victim-hurt z1)
     (fire l6)
     (victim-at z2 l3)
     (victim-hurt z2)
     (fire l2)
     (victim-at z3 l5)
     (victim-dying z3)
	;;map info

   (adjacent l2 l1)
   (adjacent l1 l2)
   (adjacent l2 l3)
   (adjacent l3 l2)
   (adjacent l3 l1)
   (adjacent l1 l3)
   (adjacent l3 l2)
   (adjacent l2 l3)
   (adjacent l4 l1)
   (adjacent l1 l4)
   (adjacent l4 l2)
   (adjacent l2 l4)
   (adjacent l4 l3)
   (adjacent l3 l4)
   (adjacent l4 l5)
   (adjacent l5 l4)
   (adjacent l6 l1)
   (adjacent l1 l6)
   (adjacent l6 l2)
   (adjacent l2 l6)
	(fire-unit-at f1 l3)
	(medical-unit-at m1 l6)
	(medical-unit-at m2 l2)
	(medical-unit-at m3 l5)
	(medical-unit-at m4 l2)
	)
 (:goal (and  (nfire l1) (nfire l6) (nfire l2)  (victim-healthy z1) (victim-healthy z2) (victim-healthy z3)))
 )
