
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Domain file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (domain graph-traversal-strips)
    (:requirements )
    (:types
        node - object
    )

    (:predicates
        (at ?x1 - node)
        (adjacent ?x1 - node ?x2 - node)
    )

    (:functions
        
    )

    
    (:action move
     :parameters (?from - node ?to - node)
     :precondition (and (adjacent ?from ?to) (at ?from))
     :effect (and
        (not (at ?from))
        (at ?to))
    ) 


    (:action noop
     :parameters (?x - node)
     :precondition (at ?x)
     :effect (and
        (at ?x))
    ) 

)