
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem graph-traversal-5x12)
    (:domain graph-traversal-strips)

    (:objects
        n_0 n_1 n_2 n_3 n_4 - node
    )

    (:init
        (adjacent n_3 n_1)
        (adjacent n_2 n_3)
        (adjacent n_1 n_3)
        (adjacent n_2 n_1)
        (adjacent n_2 n_0)
        (adjacent n_1 n_0)
        (adjacent n_0 n_1)
        (adjacent n_2 n_4)
        (adjacent n_1 n_4)
        (adjacent n_0 n_3)
        (adjacent n_4 n_0)
        (adjacent n_3 n_2)
        (at n_0)
    )

    (:goal
        (at n_4)
    )

    
    
    
)

