
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem graph-traversal-10x50)
    (:domain graph-traversal-strips)

    (:objects
        n_0 n_1 n_2 n_3 n_4 n_5 n_6 n_7 n_8 n_9 - node
    )

    (:init
        (adjacent n_2 n_7)
        (adjacent n_2 n_5)
        (adjacent n_3 n_5)
        (adjacent n_3 n_7)
        (adjacent n_5 n_3)
        (adjacent n_3 n_4)
        (adjacent n_4 n_0)
        (adjacent n_1 n_4)
        (adjacent n_4 n_8)
        (adjacent n_0 n_7)
        (adjacent n_9 n_6)
        (adjacent n_7 n_6)
        (adjacent n_6 n_3)
        (adjacent n_4 n_6)
        (adjacent n_9 n_1)
        (adjacent n_3 n_9)
        (adjacent n_3 n_8)
        (adjacent n_6 n_1)
        (adjacent n_6 n_5)
        (adjacent n_1 n_6)
        (adjacent n_1 n_0)
        (adjacent n_6 n_0)
        (adjacent n_0 n_1)
        (adjacent n_9 n_0)
        (adjacent n_8 n_7)
        (adjacent n_5 n_6)
        (adjacent n_1 n_7)
        (adjacent n_6 n_7)
        (adjacent n_3 n_2)
        (adjacent n_9 n_2)
        (adjacent n_0 n_4)
        (adjacent n_2 n_9)
        (adjacent n_4 n_9)
        (adjacent n_4 n_3)
        (adjacent n_0 n_9)
        (adjacent n_8 n_4)
        (adjacent n_2 n_3)
        (adjacent n_1 n_2)
        (adjacent n_5 n_7)
        (adjacent n_0 n_5)
        (adjacent n_0 n_2)
        (adjacent n_9 n_4)
        (adjacent n_7 n_3)
        (adjacent n_4 n_7)
        (adjacent n_4 n_5)
        (adjacent n_5 n_4)
        (adjacent n_3 n_0)
        (adjacent n_7 n_2)
        (adjacent n_0 n_3)
        (adjacent n_5 n_1)
        (at n_0)
    )

    (:goal
        (at n_9)
    )

    
    
    
)

