
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem graph-traversal-3x1)
    (:domain graph-traversal-strips)

    (:objects
        n_0 n_1 n_2 - node
    )

    (:init
        (adjacent n_0 n_1)
        (adjacent n_1 n_0)
        (adjacent n_1 n_2)
        (adjacent n_2 n_1)
        (at n_0)
    )

    (:goal
        (at n_2)
    )

    
    
    
)

