
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem reward-4x4)
    (:domain reward-strips)

    (:objects
        c_0_0 c_0_1 c_0_2 - cell
    )

    (:init
        ;; (reward c_0_1)
        (reward c_0_2)
        (at c_0_0)
        (adjacent c_0_0 c_0_1)
        (adjacent c_0_1 c_0_0)
        (adjacent c_0_2 c_0_1)
        (adjacent c_0_1 c_0_2)
    )

    (:goal
        (and (not (reward c_0_1)) (not (reward c_0_2)) )
    )

    
    
    
)

