
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Domain file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (domain gridworld-strips)
    (:requirements )
    (:types
        coordinate - object
    )

    (:constants
        
    )

    (:predicates
        (succ ?x1 - coordinate ?x2 - coordinate)
    )

    (:functions
        (xpos ) - coordinate
        (ypos ) - coordinate
        (maxpos ) - coordinate
        (goal_xpos ) - coordinate
        (goal_ypos ) - coordinate
    )

    
    (:action move_x
     :parameters (?x1 - coordinate)
     :precondition (or (succ (xpos ) ?x1) (succ ?x1 (xpos )))
     :effect (and
        (assign (xpos ) ?x1))
    ) 


    (:action move_y
     :parameters (?x1 - coordinate)
     :precondition (or (succ (ypos ) ?x1) (succ ?x1 (ypos )))
     :effect (and
        (assign (ypos ) ?x1))
    ) 

)