
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem gridworld-7x7)
    (:domain gridworld)

    (:objects
        
    )

    (:init
        (= (xpos ) 1)
        (= (ypos ) 1)
        (= (maxpos ) 7)
        (= (goal_xpos ) 7)
        (= (goal_ypos ) 7)
    )

    (:goal
        (and (= (xpos ) (goal_xpos )) (= (ypos ) (goal_ypos )))
    )

    
    (:bounds
        (coordinate - int[1..7]))
    
)

