
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem gridworld-5x5)
    (:domain gridworld-strips)

    (:objects
        c1 c2 c3 c4 c5 - coordinate
    )

    (:init
        (= (maxpos ) c5)
        (= (xpos ) c1)
        (= (ypos ) c1)
        (= (goal_xpos ) c3)
        (= (goal_ypos ) c4)
        (succ c2 c3)
        (succ c1 c2)
        (succ c4 c5)
        (succ c3 c4)
    )

    (:goal
        (and (= (xpos ) (goal_xpos )) (= (ypos ) (goal_ypos )))
    )

    
    
    
)

