
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Domain file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (domain blocksworld-atomic)
    (:requirements :equality)
    (:types
        
    )

    (:constants
        table - object
    )

    (:predicates
        (clear ?x1 - object)
        (on ?x1 - object ?x2 - object)
        (diff ?x1 - object ?x2 - object)
    )

    (:functions
        
    )

    

    
    (:action move
     :parameters (?b - object ?x - object ?y - object)
     :precondition (and (diff ?b table) (diff ?y table) (diff ?b ?y) (clear ?b) (on ?b ?x) (clear ?y))
     :effect (and
        (not (on ?b ?x))
        (clear ?x)
        (not (clear ?y))
        (on ?b ?y))
    )


    (:action move-to-table
     :parameters (?b - object ?x - object)
     :precondition (and (diff ?b table) (diff ?x table) (clear ?b) (on ?b ?x))
     :effect (and
        (not (on ?b ?x))
        (clear ?x)
        (on ?b table))
    )

)