(define (problem BLOCKS-5-CLEAR-X)
(:domain BLOCKS)
(:objects A B C D E H I J M N o p)
(:init (CLEAR M) (ON M J) (ON J I) (ON I B) (on b o) (on o p) (ONTABLE p)
       (CLEAR H) (ON H E) (ON E D) (ON D A) (on a c) (ONTABLE C)
       (CLEAR N) (ONTABLE N)
(HANDEMPTY))
(:goal (AND (ON A B)))
)
