(define (problem BLOCKS-5-CLEAR)
(:domain BLOCKS)
(:objects A B C D E)
(:init
    (ONTABLE A)
    (ONTABLE B)
    (ONTABLE C)
    (ONTABLE D)
    (ONTABLE E)
    (CLEAR A)
    (CLEAR B)
    (CLEAR C)
    (CLEAR D)
    (CLEAR E)
    (HANDEMPTY))
(:goal (AND (CLEAR A))))
